### ISSUE TITLE
init_casbin()出错

### ISSUE THREAD

**Issue by quanpower** [CoderCharm/fastapi-mysql-generator#17]
init_db时报错，

python3 init_db.py
----------开发环境启动------------
角色-超级管理员-创建成功
角色-普通用户-创建成功
用户-王小右-创建成功
用户-测试用户-创建成功
Traceback (most recent call last):
  File "init_db.py", line 93, in <module>
    init_casbin()
  File "init_db.py", line 78, in init_casbin
    e = get_casbin()
  File "/home/quanpower/fastapi_app/common/sys_casbin.py", line 27, in get_casbin
    e = casbin.Enforcer(settings.CASBIN_MODEL_PATH, adapter, True)
TypeError: __init__() takes from 1 to 3 positional arguments but 4 were given

**Comment by quanpower** [comment]
看了下，问题在这，e = casbin.Enforcer(settings.CASBIN_MODEL_PATH, adapter,True)，可能用的库有更新。把True给去掉好了，小东西就不提PR完了，麻烦小右一并改了吧，谢谢！
